### ISSUE TITLE
Windows / pop-ups have no differentiation from background

### ISSUE THREAD

**Issue by zbee** [CharlieEtienne/material-vcl#1]
As shown in HeidiSQL/HeidiSQL#485:

![heidisql](https://user-images.githubusercontent.com/1582821/51274261-ea167680-198b-11e9-9bb4-fae2b14a02a0.jpg)

Popped-up windows have no differentiation from it's background in many instances.

As @ansgarbecker pointed out, shadows may be impossible as there's a ticket about it marked `wontfix`: https://quality.embarcadero.com/browse/RSP-11751.

However a simple border could accomplish this as well.

**Comment by CharlieEtienne** [comment]
I didn't know it was marked as `wontfix` by embarcadero.

It's shame because one of the things I love in this theme is the lack of borders... 

If there are no alternatives, like a quick fix to add shadows, I would consider to add a darker or lighter border.

**Comment by zbee** [comment]
The fair lack of borders does look really good, just my 2 cents on that;
- [Material](https://material.io/design/environment/elevation.html#depicting-elevation) shows its acceptability for depicting elevation,
- There is a 3(?)px border around the query/data area, and the console area in Heidi that does look really good.

**Comment by CharlieEtienne** [comment]
You're absolutely right.

**Comment by ansgarbecker** [comment]
I planned to release HeidiSQL 10.0 these days. I'm unsure if I shall wait for a fix here. Do _you_ want to have it fixed before that release?

**Comment by CharlieEtienne** [comment]
@ansgarbecker I'll try to do it this afternoon

**Comment by CharlieEtienne** [comment]
@ansgarbecker I was quite busy today, and I won't be able to fix it before at least thursday, so maybe you shouldn't wait for me to release the new version...

**Comment by ansgarbecker** [comment]
Fair nuff.

**Comment by CharlieEtienne** [comment]
@Zbee, I wanted to have your opinion before committing : 

Lighter or Darker border ? Has it enough contrast ?

![2019-01-21_20h48_49](https://user-images.githubusercontent.com/9772943/51791547-35f3c780-21a5-11e9-9f62-39fda228d756.png)

![2019-01-21_20h50_52](https://user-images.githubusercontent.com/9772943/51791558-5a4fa400-21a5-11e9-88e9-21ae7c48bdf1.png)

**Comment by zbee** [comment]
@CharlieEtienne I think darker, but maybe 1px thicker? I believe the contrast is at least comparable to it in other places and either way it is a massive improvement - and any thicker of a border will just serve that much more.

I see that the lighter border gets lost in the text, and the darker border gets lost in background-ed elements (buttons), I believe the latter to be better, and will still be noticeable if the border is thicker.
